// Inlines the single-file widget build into a TS module the gateway imports statically
// (docs/mcp-app/PLAN.md §4.2): a missing or empty build fails HERE, at build time, never as a
// "widget not built" response at runtime.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

const frontend = fileURLToPath(new URL('../..', import.meta.url))
const source = fileURLToPath(new URL('../dist/itinerary.html', import.meta.url))
const target = fileURLToPath(new URL('../../lib/mcp/widget/generated/itinerary-v2.ts', import.meta.url))

let html
try {
  html = readFileSync(source, 'utf8')
} catch {
  console.error(`emit-module: ${relative(frontend, source)} is missing — run vite build first.`)
  process.exit(1)
}
if (html.trim().length === 0) {
  console.error(`emit-module: ${relative(frontend, source)} is empty.`)
  process.exit(1)
}

// Security requirement 8: nothing in the shipped widget may print protocol payloads. The SDK's
// default transport does (console.debug of every parsed message); main.tsx replaces it and vite
// strips payload-capable console calls. Fail loudly if either guard regresses.
const LEAKS = [/console\.(debug|log|info|trace)\(/, /Parsed message/, /Sending message/]
const leak = LEAKS.find((re) => re.test(html))
if (leak) {
  console.error(`emit-module: the widget build still contains ${leak} — private tool results could reach the browser console.`)
  process.exit(1)
}

mkdirSync(dirname(target), { recursive: true })
writeFileSync(
  target,
  '// GENERATED by npm run build:widgets — do not edit.\n'
    + `export const ITINERARY_WIDGET_HTML: string = ${JSON.stringify(html)}\n`,
)
console.log(`emit-module: wrote ${relative(frontend, target)} (${Buffer.byteLength(html)} bytes of HTML)`)
