// Publishes the widget build (docs/mcp-app/PLAN.md §4.2, v3):
//   1. checks mcp-app/dist is exactly itinerary.js + itinerary.css, both non-empty;
//   2. fails if the JS could print protocol payloads (security requirement 8);
//   3. copies both to public/mcp-widget/v3/, which Next serves (with CORS) from our origin;
//   4. writes the small HTML shell the gateway imports statically, with %ASSET_BASE% placeholders
//      that lib/mcp/widget/itinerary-resource.ts fills with the configured origin at read time.
// A missing or wrong build fails HERE, at build time, never as a "widget not built" response.
import { copyFileSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

export const WIDGET_VERSION = 'v3'
const ASSETS = ['itinerary.css', 'itinerary.js']

const frontend = fileURLToPath(new URL('../..', import.meta.url))
const dist = fileURLToPath(new URL('../dist', import.meta.url))
const publicDir = fileURLToPath(new URL(`../../public/mcp-widget/${WIDGET_VERSION}`, import.meta.url))
const target = fileURLToPath(new URL(`../../lib/mcp/widget/generated/itinerary-${WIDGET_VERSION}.ts`, import.meta.url))

function fail(message) {
  console.error(`emit-module: ${message}`)
  process.exit(1)
}

let files
try {
  files = readdirSync(dist).sort()
} catch {
  fail(`${relative(frontend, dist)} is missing — run vite build first.`)
}
// Exactly two files: a split chunk or an emitted image/font would be fetched by a RELATIVE URL,
// which does not resolve inside the host's sandboxed frame.
if (files.join(',') !== ASSETS.join(',')) {
  fail(`${relative(frontend, dist)} must contain exactly ${ASSETS.join(' + ')}; found ${files.join(', ') || 'nothing'}.`)
}
const contents = Object.fromEntries(ASSETS.map((name) => [name, readFileSync(join(dist, name), 'utf8')]))
for (const [name, text] of Object.entries(contents)) {
  if (text.trim().length === 0) fail(`${name} is empty.`)
}

// Security requirement 8: nothing in the shipped widget may print protocol payloads. The SDK's
// default transport does (console.debug of every parsed message); main.tsx replaces it and vite
// strips payload-capable console calls. Fail loudly if either guard regresses.
const LEAKS = [/console\.(debug|log|info|trace)\(/, /Parsed message/, /Sending message/]
const leak = LEAKS.find((re) => re.test(contents['itinerary.js']))
if (leak) fail(`itinerary.js still contains ${leak} — private tool results could reach the browser console.`)

rmSync(publicDir, { recursive: true, force: true })
mkdirSync(publicDir, { recursive: true })
for (const name of ASSETS) copyFileSync(join(dist, name), join(publicDir, name))

// crossorigin: a module script is always CORS-fetched from the sandbox's opaque origin; marking the
// stylesheet too keeps both requests in the same (credential-less) mode.
const shell = [
  '<!doctype html>',
  '<html lang="en">',
  '<head>',
  '<meta charset="UTF-8" />',
  '<meta name="viewport" content="width=device-width, initial-scale=1.0" />',
  '<title>Astrail itinerary</title>',
  '<link rel="stylesheet" crossorigin="anonymous" href="%ASSET_BASE%/itinerary.css" />',
  '</head>',
  '<body>',
  '<div id="astrail-itinerary-root"></div>',
  '<script type="module" crossorigin="anonymous" src="%ASSET_BASE%/itinerary.js"></script>',
  '</body>',
  '</html>',
  '',
].join('\n')

mkdirSync(dirname(target), { recursive: true })
writeFileSync(
  target,
  '// GENERATED by npm run build:widgets — do not edit.\n'
    + `/** The widget's assets are served from \`<resource origin>${'/mcp-widget/' + WIDGET_VERSION}/\` (public/). */\n`
    + `export const ITINERARY_WIDGET_ASSET_PATH = ${JSON.stringify(`/mcp-widget/${WIDGET_VERSION}`)}\n`
    + `/** HTML shell; %ASSET_BASE% is replaced with \`<resource origin>\${ITINERARY_WIDGET_ASSET_PATH}\`. */\n`
    + `export const ITINERARY_WIDGET_SHELL: string = ${JSON.stringify(shell)}\n`,
)
const sizes = ASSETS.map((name) => `${name} ${Buffer.byteLength(contents[name])} B`).join(', ')
console.log(`emit-module: wrote ${relative(frontend, target)} (shell ${Buffer.byteLength(shell)} B); published ${sizes} to ${relative(frontend, publicDir)}/`)
